# Settings for connect with database per environment
connections:
  production:
    adapter: mysql
    host: localhost
    port: 3306
    user: admin
    pass: pass
    base: gf_production
  development:
    adapter: mysql
    host: localhost
    port: 3306
    user: admin
    pass: pass
    base: gf_development
  test:
    adapter: mysql
    host: localhost
    port: 3306
    user: admin
    pass: pass
    base: gf_test